

public class ExceptionTest2 {

	public void func() {
		
	}
	
	
	public static void main(String[] args) {
		
	}

}
